---
    - name: Desactivar SELinux del arranque
      selinux:
        state: disabled
    - name: Desactivar SELinux en el momento
      selinux:
       policy: targeted
       state: permissive
    - name: Apagar Firewalld
      systemd:
       state: stopped
       name: firewalld
       enabled: False
